name: Cron

on: 
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest tag
        id: latest_tag
        run: |
          git fetch --depth=1 origin "+refs/tags/*:refs/tags/*"
          latest_commit=$(git rev-list --tags --max-count=1)
          latest_tag=$(git describe --tags "$latest_commit")
          echo "::set-output name=tag::$latest_tag"
      
      - name: Display latest tag
        run: |
          echo "Latest tag is ${{ steps.latest_tag.outputs.tag }}"

      - uses: actions/checkout@v3
        with:
          ref: ${{steps.latest_tag.outputs.tag}}

      - name: Build
        id: build
        run: go build -v ./...

      - name: Test
        id: test
        run: go test -v ./...

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.18

      - name: Slack Notify - Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-action-notify-test
          SLACK_COLOR: ${{job.status}}
          SLACK_ICON: https://github.com/github.png
          SLACK_USERNAME: Github Actions
          SLACK_TITLE: 'Job ${{github.job}}: ${{ github.repository }}'
          SLACK_MESSAGE: 'Success'
          SLACK_FOOTER: 'Linked Repo - <${{ github.event.repository.html_url }}|${{ github.repository }}>'

      - name: Slack Notify - Build Failure
        if: failure() && steps.build.conclusion == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-action-notify-test
          SLACK_COLOR: ${{job.status}}
          SLACK_ICON: https://github.com/github.png
          SLACK_USERNAME: Github Actions
          SLACK_TITLE: 'Job ${{github.job}}: ${{ github.repository }}'
          SLACK_MESSAGE: 'Build Failed'
          SLACK_FOOTER: 'Linked Repo - <${{ github.event.repository.html_url }}|${{ github.repository }}>'

      - name: Slack Notify - Test Failure
        if: failure() && steps.test.conclusion == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: github-action-notify-test
          SLACK_COLOR: ${{job.status}}
          SLACK_ICON: https://github.com/github.png
          SLACK_USERNAME: Github Actions
          SLACK_TITLE: 'Job ${{github.job}}: ${{ github.repository }}'
          SLACK_MESSAGE: 'Test Failed'
          SLACK_FOOTER: 'Linked Repo - <${{ github.event.repository.html_url }}|${{ github.repository }}>'
